name: AI4Project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.12
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - tqdm
  - requests
  - regex
  - transformers
  - datasets
  - accelerate
  - aiohttp
  - jinja2
  - pyyaml
  - huggingface_hub
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - pip:
      - optree
      - safetensors
      - tokenizers
